name: Deploy app to azure
on:
    workflow_call: 
        inputs:
            AZURE_WEBAPP_NAME:
                required: true
                type: string
            AZURE_WEBAPP_PACKAGE_PATH:
                required: true
                type: string
                default: './'
            DEPLOY_ENV:
                required: true
                type: string        
        secrets:
          web-app-profile:
            required: true

jobs:
  deploy:
    name: ${{inputs.DEPLOY_ENV}}
    runs-on: windows-latest   
    steps:
    - name: 'Download build artifacts'
      uses: actions/download-artifact@v2
      with:
        name: 'webapp-artifact'
        path: '${{ inputs.AZURE_WEBAPP_PACKAGE_PATH }}'

    - name: 'Run Azure webapp deploy'
      uses: azure/webapps-deploy@v2
      with: 
        app-name: ${{ inputs.AZURE_WEBAPP_NAME }} # Replace with your app name
        slot-name: ${{ inputs.DEPLOY_ENV }}
        publish-profile: ${{ secrets.web-app-profile  }} # Define secret variable in repository settings as per action documentation
        package: '${{ inputs.AZURE_WEBAPP_PACKAGE_PATH }}'