name: Build and deploy Java Application - Assignment 2 - Rajkumar

on:
  workflow_call: 
    inputs:
        java-version:
            required: true
            type: string
        pom-path:
            required: true
            type: string
        app-name:
            required: true
            type: string
        package-path:
            required: true
            type: string
        artifact-name:
            required: true
            type: string
        env-name:
            required: true
            type: string
        slot-name:
            required: true
            type: string
    secrets:
        azure-credentials:
            required: true

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4
    
          - name: Set up Java version
            uses: actions/setup-java@v1
            with:
              java-version: ${{ inputs.java-version }}

          - name: Cache Maven packages
            id: maven-cache
            uses: actions/cache@v2
            with:
                path: ~/.m2
                key: ${{ runner.os }}-rajkumar-${{ hashFiles('**/pom.xml') }}
                restore-keys: ${{ runner.os }}-rajkumar

          - name: Display cache output
            run: |
                echo '${{ toJSON(steps.maven-cache.outputs) }}'
          - name: Build with Maven
            run: mvn -f ${{ inputs.pom-path }} clean install
    
          - name: Upload artifact for deployment job
            uses: actions/upload-artifact@v3
            with:
              name: ${{ inputs.artifact-name }}
              path: ${{ inputs.package-path }}
    
    deploy:
        runs-on: ubuntu-latest
        needs: build
        environment:
            name: ${{ inputs.env-name }}
            url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

        steps:
        - name: Download artifact from build job
          uses: actions/download-artifact@v3
          with:
            name: ${{ inputs.artifact-name }}
        - name: Deploy to Azure Web App
          id: deploy-to-webapp
          uses: azure/webapps-deploy@v2
          with:
            app-name: ${{ inputs.app-name }}
            slot-name: ${{ inputs.slot-name }}
            package: '*.jar'
            publish-profile: ${{ secrets.azure-credentials }}