name: Deploy .NET App Template

on:
    workflow_call:       
        secrets:
            SONAR_TOKEN:
                required: true
            github_token:
                required: true


jobs:
  codeql-analysis:
    uses: rajkumar-r-org/build-template/.github/workflows/codeql/codeql-analysis.yml@main
    name: CodeQL
    permissions:
        actions: read
        security-events: write
        contents: read
  
  sonar-scan:
    uses: rajkumar-r-org/build-template/.github/workflows/sonar-scan/sonar-analysis.yml@main
    name: Sonar-Scan
    with:
        SONAR_TOKEN: ${{secrets.SONAR_TOKEN}}
        GITHUB_TOKEN: ${{secrets.github_token}}

  build:
    name: Build
    needs: [codeql-analysis,sonar-scan]
    runs-on: windows-latest
    steps:

    # checkout the repo
    - uses: actions/checkout@v3 
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0.x'

    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --no-build

    - name: Publish
      run: dotnet publish --no-build --output ./publish

    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v3
      with:
        name: 'webapp-artifact'
        path: ./publish
